const val PREFERENCE_NAME = "MY_APP_PREF"

const val PREF_LOGGED_IN = "PREF_LOGGED_IN"
const val PREF_IS_LANGUAGE_SELECTED = "PREF_IS_LANGUAGE_SELECTED"
const val PREF_CURRENT_SELECTED_LANGUAGE = "PREF_CURRENT_SELECTED_LANGUAGE"
const val PREF_CONTACT_EMAIL = "PREF_CONTACT_EMAIL"
const val PREF_SHARE_MESSAGE = "PREF_SHARE_MESSAGE"
const val PREF_MINIMUM_APP_VERSION = "PREF_MINIMUM_APP_VERSION"